---
from: squash@vecna.com
domain: vecna.com
strategy: smtp
smtp_settings:
  address: OVERRIDE
  port: '25'
  domain: vecna.com
  user_name: 
  password: 
  authentication: none
  enable_starttls_auto: true
